version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 559050219152.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nodeapp .
      - docker tag nodeapp:latest 559050219152.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
      - echo Pushing the Docker image to ECR...
      - docker push 559050219152.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
  post_build:
    commands:
      - echo Setting up Kubernetes config...
      - aws eks update-kubeconfig --name your-cluster-name --region us-east-1
      - echo Deploying to EKS...
      - kubectl set image deployment/nodeapp nodeapp=559050219152.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest

artifacts:
  files:
    - deployment1.yaml
