version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nodeapp .
      - docker tag nodeapp:latest 559050219152.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
      - docker push 559050219152.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
  post_build:
    commands:
      - echo Deploying to EKS...
      - kubectl set image deployment/nodeapp nodeapp=559050219152.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest

artifacts:
  files:
    - deployment1.yaml
