version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 559050219152.dkr.ecr.us-east-1.amazonaws.com/nodeapp
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t node-app .
      - docker tag node-app:latest 559050219152.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 559050219152.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
      - echo Updating Kubernetes Deployment...
      - kubectl set image deployment/node-app node-app=559050219152.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
