apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 559050219152.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
        ports:
        - containerPort: 3000 # Adjust to your app's port
